// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzcGGsdBylOovUbyvv_6mgc7F-JKH1TDo',
    appId: '1:153025127650:web:c1b0af6fde361b7d24aabb',
    messagingSenderId: '153025127650',
    projectId: 'ok-multipl-poker',
    authDomain: 'ok-multipl-poker.firebaseapp.com',
    storageBucket: 'ok-multipl-poker.firebasestorage.app',
    measurementId: 'G-K1JDNMYDV6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb3btB0vnOa5WldP4Q4tKWPxGWyvOB8RA',
    appId: '1:153025127650:android:07d24ad661fe66ae24aabb',
    messagingSenderId: '153025127650',
    projectId: 'ok-multipl-poker',
    storageBucket: 'ok-multipl-poker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfGIzDJrh2Z2V4dK28rahP9DBzVbMEVgg',
    appId: '1:153025127650:ios:bbf2043c061cac1924aabb',
    messagingSenderId: '153025127650',
    projectId: 'ok-multipl-poker',
    storageBucket: 'ok-multipl-poker.firebasestorage.app',
    iosBundleId: 'com.example.okMultiplPoker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6KsB6n5jsvLf2apddzFIoo2ZPbbwMbdk',
    appId: '1:279016704934:ios:faac0650d42695f210dd67',
    messagingSenderId: '279016704934',
    projectId: 'card-game-eea6d',
    storageBucket: 'card-game-eea6d.appspot.com',
    iosBundleId: 'com.example.card.RunnerTests',
  );
}




// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//               'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//               'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDrAkyM6h9iUzWsrN7jEu1RtclS_UvBWS0',
//     appId: '1:527731905963:web:25cc9ec6a727daf4d76eee',
//     messagingSenderId: '527731905963',
//     projectId: 'mystorage-2840b',
//     authDomain: 'mystorage-2840b.firebaseapp.com',
//     storageBucket: 'mystorage-2840b.firebasestorage.app',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDvuxHe7FNF_aUJoJf4LZQH4skcwY85T5M',
//     appId: '1:527731905963:android:bbd1e7322698eb42d76eee',
//     messagingSenderId: '527731905963',
//     projectId: 'mystorage-2840b',
//     storageBucket: 'mystorage-2840b.firebasestorage.app',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCfIfpwyrHJikT2RIK4xtqkIJ_t-_KD3-s',
//     appId: '1:527731905963:ios:f2efc39f2307c1f4d76eee',
//     messagingSenderId: '527731905963',
//     projectId: 'mystorage-2840b',
//     storageBucket: 'mystorage-2840b.firebasestorage.app',
//     iosBundleId: 'com.example.okMultiplPoker',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyD6KsB6n5jsvLf2apddzFIoo2ZPbbwMbdk',
//     appId: '1:279016704934:ios:faac0650d42695f210dd67',
//     messagingSenderId: '279016704934',
//     projectId: 'card-game-eea6d',
//     storageBucket: 'card-game-eea6d.appspot.com',
//     iosBundleId: 'com.example.card.RunnerTests',
//   );
// }